# Generated by Django 5.1.6 on 2025-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('In-Person', 'In-Person')], max_length=10)),
                ('participants', models.JSONField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('Applied Biology Program', 'Applied Biology Program'), ('Applied Chemistry', 'Applied Chemistry'), ('Applied Physics', 'Applied Physics'), ('Applied Geology', 'Applied Geology'), ('Applied Mathematics', 'Applied Mathematics'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Pharmacy Program', 'Pharmacy Program'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electrical Power and Control Engineering', 'Electrical Power and Control Engineering'), ('Software Engineering', 'Software Engineering'), ('Architecture', 'Architecture'), ('Civil Engineering', 'Civil Engineering'), ('Water Resources Engineering', 'Water Resources Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Material Science and Engineering', 'Material Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], default=None, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events_table',
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('professional_experiences', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'internship_application_table',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_id', models.CharField(max_length=100)),
                ('alumni_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_application_table',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('internship', 'Internship'), ('Job', 'Job')], max_length=10)),
                ('departments', models.JSONField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'opportunities_table',
            },
        ),
        migrations.CreateModel(
            name='ResourceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Applied Biology Program', 'Applied Biology Program'), ('Applied Chemistry', 'Applied Chemistry'), ('Applied Physics', 'Applied Physics'), ('Applied Geology', 'Applied Geology'), ('Applied Mathematics', 'Applied Mathematics'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Pharmacy Program', 'Pharmacy Program'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electrical Power and Control Engineering', 'Electrical Power and Control Engineering'), ('Software Engineering', 'Software Engineering'), ('Architecture', 'Architecture'), ('Civil Engineering', 'Civil Engineering'), ('Water Resources Engineering', 'Water Resources Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Material Science and Engineering', 'Material Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('text', 'Text'), ('book', 'Book'), ('ppt', 'PowerPoint'), ('file', 'File'), ('url', 'URL')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_share_table',
            },
        ),
    ]
