# Generated by Django 5.1.6 on 2025-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='sender',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
