# Generated by Django 5.1.6 on 2025-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Picture/'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='work_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
