# Generated by Django 5.1.6 on 2025-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alumniprofile_bio_alumniprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Picture/Alumni/'),
        ),
    ]
