# Generated by Django 5.1.6 on 2025-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_alumniprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Profile_Picture/Alumni/'),
        ),
    ]
