# Generated by Django 5.1.6 on 2025-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_alumniprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='achievements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='activities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='professional_experiences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Picture/Srudent/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
