# Generated by Django 5.1.6 on 2025-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
