# Generated by Django 5.1.6 on 2025-05-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alumniprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Picture/Company/'),
        ),
    ]
