# Generated by Django 5.1.6 on 2025-05-17 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0009_companyprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_resource', 'New Resource Shared'), ('connect_request', 'New Connection Request'), ('connect_accept', 'Connection Accepted'), ('event_announcement', 'New Event Announcement'), ('event_update', 'Event Update'), ('event_reminder', 'Event Reminder'), ('event_feedback', 'Event Feedback'), ('event_cancelled', 'Event Cancelled'), ('event_registration', 'Event Registration'), ('event_participant', 'New Event Participant'), ('new_message', 'New Message')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
