# Generated by Django 5.1.6 on 2025-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_resource', 'New Resource Shared'), ('connect_request', 'New Connection Request'), ('connect_accept', 'Connection Accepted'), ('event_announcement', 'New Event Announcement'), ('new_message', 'New Message'), ('new_opportunity', 'New Opportunity'), ('internship_application_status', 'Internship Application Status'), ('job_application', 'Job Application'), ('job_application_status', 'Job Application Status'), ('feedback_received', 'Feedback Received'), ('feedback_request', 'Feedback Request'), ('feedback_reminder', 'Feedback Reminder'), ('event_reminder', 'Event Reminder')], max_length=50),
        ),
    ]
